services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2025:2025"
    volumes:
      - ./content:/usr/src/content:ro
    networks:
      - tunnel_net

  cloudflared:
    image: cloudflare/cloudflared:latest
    depends_on:
      - backend
    command: tunnel --url http://backend:2025
    networks:
      - tunnel_net
    restart: unless-stopped

networks:
  tunnel_net:
    driver: bridge
