#!/bin/sh

set -e

echo "[ husky-rs * ] Running commitlint hook."
cat .git/COMMIT_EDITMSG | commitlint --config ./.commitlintrc.yml

echo "[ husky-rs * ] Running lint and format."
cargo fmt -- --check
cargo clippy -- -D warnings
